name: build

on:
  push:
  pull_request:

jobs:
    tests:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.2, 8.3]
                laravel: [7.*, 8.*, 9.*, 10.*]
                dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest]
                include:
                  - laravel: 10.*
                    testbench: 8.*
                  - laravel: 9.*
                    testbench: 7.*
                  - laravel: 8.*
                    testbench: 6.*
                  - laravel: 7.*
                    testbench: 5.*

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "illuminate/contracts=${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest

    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.1
                  extensions: dom, curl, libxml, mbstring, zip
                  tools: composer:v2
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest --coverage-text --coverage-clover=coverage.clover

            - name: Upload coverage
              run: |
                vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

    linting:
        runs-on: ubuntu-latest

        name: Linting

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  tools: composer:v2
                  coverage: none

            - name: Install dependencies
              run: |
                  composer update --prefer-stable --prefer-dist --no-interaction

            - name: Execute Duster
              run: vendor/bin/duster lint -u tlint,phpcodesniffer,pint,phpstan -vvv
